replicaCount: 1

image:
  name: alterusio/cert-manager-secret-webhook
  tag: "1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP

namespaceSelector: "kubed-sync=true"