apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-secret-webhook
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cert-manager-secret-webhook
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: "WEBHOOK_PORT"
              value: "443"
            - name: "WEBHOOK_CERT"
              value: "/etc/webhook/certs/tls.crt"
            - name: "WEBHOOK_KEY"
              value: "/etc/webhook/certs/tls.key"
            - name: "NAMESPACE_SELECTOR"
              value: {{ .Values.namespaceSelector | quote }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ template "webhook.name" . }}-secret-certs
